# Try downloading fonts and putting in static folder then loading into css

languageCode = "en-us"
title = "Brendan Cooley"
theme = "crab"
baseurl = "http://brendancooley.com"

[params]
first_name = "Brendan"
last_name = "Cooley"
custom_css = ["css/cooley.css"]
description = "Ph.D. Candidate | Department of Politics | Princeton University"
# logoimage = "images/logo.jpg"
# copyright = "foo"

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo

[permalinks]
# notes = "/notes/"

[taxonomies]
tags = "tags"
